# Dynamic memory management
# Reference: https://en.cppreference.com/w/cpp/memory

cc_binary(
    name = "memory",
    srcs = ["memory_demo.cc"],
    deps = [
        "//classes:common",
        "//meta:common",
    ],
)
