# Containers library
# Reference: https://en.cppreference.com/w/cpp/container

cc_binary(
    name = "associative",
    srcs = ["associative_demo.cc"],
    deps = ["//meta:common"],
)

cc_binary(
    name = "sequence",
    srcs = ["sequence_demo.cc"],
    deps = ["//meta:common"],
)

cc_binary(
    name = "unordered_associative",
    srcs = ["unordered_associative_demo.cc"],
    deps = ["//meta:common"],
)
