# Containers library
# Reference: https://en.cppreference.com/w/cpp/container

cc_binary(
    name = "associative",
    srcs = ["associative.cc"],
    deps = ["//templates:common"],
)

cc_binary(
    name = "sequence",
    srcs = ["sequence.cc"],
    deps = ["//templates:common"],
)

cc_binary(
    name = "unordered_associative",
    srcs = ["unordered_associative.cc"],
    deps = ["//templates:common"],
)
