# library of common definitions

cc_library(
    name = "lib",
    srcs = [
        "book.cc",
        "file_handle.cc",
        "person.cc",
        "student.cc",
    ],
    hdrs = [
        "book.h",
        "file_handle.h",
        "person.h",
        "student.h",
    ],
    visibility = ["//visibility:public"],
)
